### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by darimary76** [svind1er/Bonelab-Mods#1]
Master Chief v8 WIP by Svindler QUEST.rar
Kermit The Frog by Svindler QUEST.rar
Asuka_Langley_Sohryu_by_Carpe_DMT_Quest.7z
Harry_Du_Bois_by_Carpe_DMT_Quest.zip

Fail to extract with winrar and failed to extract with winrar and 7zip
Error: not archives found

**Comment by WasabiThumb** [comment]
Worked fine for me
